### ISSUE TITLE
Bug: Bender sources may start with `false`

### ISSUE THREAD

**Issue by flaviens** [pulp-platform/bender#114]
Hi!

## Brief

Since a recent version of Bender, a parasitic `false` appears at the beginning of `bender.sources`, making them uninterpretable by Morty. I tried at least with the current `0.27.0` version.

The output source manifest is as below, where the first line is not wanted:

```
false
[
  {
    "package": "ariane",
    "independent": false,
    "target": "all(*, all(*))",
...
```

## How to reproduce

```
git clone https://github.com/openhwgroup/cva6.git
bender sources -f -t ariane > my.sources
head my.sources
```

And Morty (at least `0.8.0`) does not like it:
```
morty -f my.sources
error parsing json in `my.sources`: invalid type: boolean `false`, expected a sequence at line 1 column 5
```

## Suggestion

There was a similar issue with similar tools (sv2v I think). I'd suggest either or both:

* adding a `-o target_file` (or another letter) to avoid using stdout as the  way of writing to the output file.
* removing what seems to be a debug print.

Thanks!
Flavien

**Comment by micprog** [comment]
Does #115 fix your issue?

**Comment by flaviens** [comment]
Looks very probable, thanks!
