### ISSUE TITLE
bender clone command should implicitly update dependency path

### ISSUE THREAD

**Issue by meggiman** [pulp-platform/bender#46]
Trying out the new bender `clone` command I noticed that while bender clone <package> name successfully checks out the package and registers it in the Bender.local file it does not update the path corresponding to the just cloned package. This can be forced with a `bender update` but intuitively I would have expected that:

`bender clone my_package`
immediately followed by
`bender path my_package`

would yield `working_dir/my_package`. However, right now the path command still returns the hidden internal git directory until I manually call `bender update`...

**Comment by fabianschuiki** [comment]
This is an excellent point. We should probably trigger a dependency re-resolution, or if we ever get to improve the dependency resolver a bit, unlock the corresponding dependency and cause it to re-resolve to the path. /cc @micprog
