### ISSUE TITLE
Slow 'bender update'

### ISSUE THREAD

**Issue by FrancescoConti** [pulp-platform/bender#50]
`bender update` seems to be very slow on CentOS machines (for a benderized PULP cluster). Specifically, it seems to hang for 2-3 minutes without printing anything just after it clones all repos.
Any idea about possible causes / workarounds / solutions? Unfortunately, I could not really dig into the bowels of the issue... but it doesn't look like an expected behavior.

**Comment by accuminium** [comment]
Thanks for reporting this issue, @FrancescoConti! This should be fixed in #51, which has been released with v0.23.0.  Please try this or a later version and let us know if the problem persists.
